import ts from "typescript-parser";

export const STREAM_LIFECYCLE_PROFILE = "lenso.provider-stream-cleanup@1";

// Exact behavior emitted by the supported current contract-codegen projection.
// Normalize TS/JS syntax, never silently patch an unknown generator/runtime.
const ORIGINAL_LOWERING = `function lowerProviderStream<Message, DomainError>(stream: ProviderStream<Message, DomainError>): StreamSession<Message, DomainError> {
  if (!isAsyncIterable<Message>(stream)) return stream;
  const iterator = stream[Symbol.asyncIterator]();
  let cancelled = false;
  return {
    async send() { throw new ServerOutputStreamInputError("server-output stream does not accept inbound messages"); },
    async receive() {
      if (cancelled) return { kind: "terminal", outcome: { ok: true } };
      const next = await iterator.next();
      return next.done
        ? { kind: "terminal", outcome: { ok: true } }
        : { kind: "message", message: next.value };
    },
    async closeSend() {},
    cancel() {
      cancelled = true;
      const closing = iterator.return?.();
      if (closing !== undefined) void Promise.resolve(closing).catch(() => undefined);
    },
  };
}`;

function normalized(source: string): string {
  return ts.transpileModule(source, {
    compilerOptions: { target: ts.ScriptTarget.ES2022, removeComments: true },
  }).outputText;
}
const expected = normalized(ORIGINAL_LOWERING);

/** @internal Execution packaging of a recognized generated JS/TS projection. */
export function lowerGeneratedStreamModule(path: string, contents: string): string {
  if (!contents.startsWith("/* @generated by lenso-contract-codegen; do not edit. */")) return contents;
  const source = ts.createSourceFile(path, contents, ts.ScriptTarget.Latest, true);
  const lowering = source.statements.find((node): node is ts.FunctionDeclaration =>
    ts.isFunctionDeclaration(node) && node.name?.text === "lowerProviderStream");
  if (!lowering) return contents;
  if (!lowering.body || normalized(lowering.getText(source)) !== expected) {
    throw new Error(`${path}: unsupported generated Stream lowering; expected the current codegen server-output projection`);
  }
  const edits: { start: number; end: number; contents: string }[] = [{
    start: lowering.body.getStart(source), end: lowering.body.end,
    contents: '{ return lensoContractRuntime.lowerProviderStreamWithCleanup(stream, () => new ServerOutputStreamInputError("server-output stream does not accept inbound messages")); }',
  }];
  let bindings = 0, contracts = 0;
  function visit(node: ts.Node): void {
    if (ts.isMethodDeclaration(node) && node.name.getText(source) === "cancel" &&
        node.body && /^\{\s*stream\.cancel\(\);\s*\}$/.test(node.body.getText(source)) &&
        ts.isObjectLiteralExpression(node.parent)) {
      bindings++;
      edits.push({ start: node.body.getStart(source), end: node.body.end, contents: "{ return stream.cancel(); }" });
      edits.push({ start: node.parent.getStart(source) + 1, end: node.parent.getStart(source) + 1, contents: "\nclosed: stream.closed,\n" });
    }
    if (ts.isObjectLiteralExpression(node) && node.properties.some(property =>
      ts.isPropertyAssignment(property) && property.name.getText(source) === "kind" &&
      ts.isStringLiteral(property.initializer) && property.initializer.text === "lenso.capability")) {
      contracts++;
      edits.push({ start: node.getStart(source) + 1, end: node.getStart(source) + 1, contents: ` streamLifecycleProfile: "${STREAM_LIFECYCLE_PROFILE}", ` });
    }
    ts.forEachChild(node, visit);
  }
  visit(source);
  if (!bindings || !contracts) throw new Error(`${path}: generated Stream projection lacks supported binding/contract boundaries`);
  let output = contents;
  for (const edit of edits.sort((a, b) => b.start - a.start)) {
    output = output.slice(0, edit.start) + edit.contents + output.slice(edit.end);
  }
  return output;
}
